"""add sort_author to book_metadata

Revision ID: 419d6ff200e8
Revises: 44f47329e378
Create Date: 2026-03-26 23:47:18.063695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419d6ff200e8'
down_revision: Union[str, None] = '44f47329e378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_metadata', sa.Column('sort_author', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_metadata', 'sort_author')
    # ### end Alembic commands ###
